[CmdletBinding()]
param(
    [string]$OtelDemoPath,
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if ([string]::IsNullOrWhiteSpace($OtelDemoPath)) {
    $OtelDemoPath = Join-Path (Split-Path -Parent $repoRoot) "opentelemetry-demo"
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $repoRoot ".env.local-full-acceptance"
}

function Get-OtelMappedPort {
    param(
        [Parameter(Mandatory = $true)][string]$Service,
        [Parameter(Mandatory = $true)][int]$ContainerPort
    )

    $mapping = & docker compose -f compose.yaml -f compose.observability.yaml -f compose.extras.yaml port $Service $ContainerPort
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($mapping)) {
        throw "OpenTelemetry Demo service '$Service' does not have a published port. Start the pinned Demo stack first."
    }
    $hostPort = ($mapping | Select-Object -First 1).Trim().Split(':')[-1]
    $parsedPort = 0
    if (-not [int]::TryParse($hostPort, [ref]$parsedPort)) {
        throw "Cannot parse the published port for OpenTelemetry Demo service '$Service'."
    }
    return [int]$hostPort
}

function Assert-OtelHttpEndpoint {
    param(
        [Parameter(Mandatory = $true)][int]$Port,
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Service
    )

    try {
        $response = Invoke-WebRequest -UseBasicParsing -TimeoutSec 5 -Uri "http://127.0.0.1:$Port$Path"
    }
    catch {
        throw "OpenTelemetry Demo service '$Service' is not reachable on its published port. Start and health-check the Demo stack first."
    }
    if ($response.StatusCode -lt 200 -or $response.StatusCode -ge 300) {
        throw "OpenTelemetry Demo service '$Service' is not healthy."
    }
}

$resolvedDemoPath = (Resolve-Path -LiteralPath $OtelDemoPath).Path
Push-Location $resolvedDemoPath
try {
    $openSearchPort = Get-OtelMappedPort -Service "opensearch" -ContainerPort 9200
    $prometheusPort = Get-OtelMappedPort -Service "prometheus" -ContainerPort 9090
}
finally {
    Pop-Location
}
Assert-OtelHttpEndpoint -Port $openSearchPort -Path "/_cluster/health" -Service "opensearch"
Assert-OtelHttpEndpoint -Port $prometheusPort -Path "/-/ready" -Service "prometheus"

$targetConfig = @'
[{"target_id":"3a6f0a82-df13-4240-a41c-36db982bce8e","slug":"otel-demo-local-full-acceptance","display_name":"OpenTelemetry Demo Local Full Acceptance","description":"Read-only OpenTelemetry Demo target for the V2 local full-core-flow acceptance.","environment":"local","services":[{"name":"checkout","display_name":"Checkout","description":"OpenTelemetry Demo checkout service."}],"logs":{"enabled":true,"adapter_type":"opensearch","provider_config_ref":"otel-demo-local-logs"},"metrics":{"enabled":true,"adapter_type":"prometheus","provider_config_ref":"otel-demo-local-metrics"}}]
'@.Trim()

$providerConfigs = @'
[{"provider_config_ref":"otel-demo-local-logs","adapter_type":"opensearch","backend_config_key":"otel-demo-local-logs-backend"},{"provider_config_ref":"otel-demo-local-metrics","adapter_type":"prometheus","backend_config_key":"otel-demo-local-metrics-backend"}]
'@.Trim()

$providerBackendConfigs = "[{`"backend_config_key`":`"otel-demo-local-logs-backend`",`"adapter_type`":`"opensearch`",`"endpoint`":`"http://host.docker.internal:$openSearchPort`"},{`"backend_config_key`":`"otel-demo-local-metrics-backend`",`"adapter_type`":`"prometheus`",`"endpoint`":`"http://host.docker.internal:$prometheusPort`"}]"

$outputDirectory = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
    New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}

$content = @(
    "# Generated by scripts/New-V2LocalFullAcceptanceConfig.ps1. Do not commit this file.",
    "# It contains no model or provider credential; keep LLM_* and EMBEDDING_* in .env.",
    "DEVSUPPORT_INVESTIGATION_TARGET_CONFIGS=$targetConfig",
    "DEVSUPPORT_PROVIDER_CONFIGS=$providerConfigs",
    "DEVSUPPORT_PROVIDER_BACKEND_CONFIGS=$providerBackendConfigs"
)
Set-Content -LiteralPath $OutputPath -Value $content -Encoding utf8

Write-Output "Generated non-secret local full-acceptance target overlay for otel-demo-local-full-acceptance."
